### PR TITLE
Create ESP32_Thermostat_latest_new.ino

### PR DESCRIPTION
**Pull request by robertopuhan777**
I added a few lines (haikus) since original code tends to freeze - Robert Puhan wildheart@poetic.com 
So additional functions added - javascript picsum backgrounds, two aditional relays, target humidity, readings for pressure, dewpoint, altitude, wifi signal, histeresys for humidity, 
calibration for temperature and humidity, javascript refreshing for all website elements (except graphs) - no more freezed up actions, fontawesome, login for website, internet world radios 
on website RADIO LEMON, secondary sensor in bottom slide box, fullscreen button and last but not least jquery javascript...

I just added a few cruicial things to be able to use this awesome peace of coding by David

Feel free to use it if you dare :)

### CODE REVIEW

**Comment by PetePenquin** [comment]
Hi, thanks for the effort you made. I really appreciated it.

However, as the orginal code creates a server, your's does not (with me), i can see it on my wireless network, but i can not reach it. 

Any idea where i go wrong. I changend ssid/password + login+ password and your ip:port/relay/on in both my external ip as my internal ip. post = 8080 and port forward it.

Thanks in advance.
Pete

**Comment by G6EJD** [comment]
Are you accessing the server with 
http://ip_address:8080/?
It will be either a browser problem or your port forwarding rule.
http://thermostat.local:8080/

**Comment by PetePenquin** [comment]
> Are you accessing the server with http://ip_address:8080/? It will be either a browser problem or your port forwarding rule. http://thermostat.local:8080/

I'm doing this from within my own network, so i tried internal adress :80 and 8080. both not working.

And while doing an ip search
Knipsel

.144 is the 'old code', 167 is the new.
??

**Comment by G6EJD** [comment]
Are you sure your on the same network as the ESP when trying to access it?

**Comment by Phanegem** [comment]
> Are you sure your on the same network as the ESP when trying to access it?

Yes i am. I'll try to use it at a friends house to rule out network problems

**Comment by G6EJD** [comment]
This is not a code error/issue. You should try the original code using port 80 to ensure that is working. Also you may have to revert the compiler version especially if using an ESP8266 back to 2.6 as there are network issues with the latest versions.

**Comment by Phanegem** [comment]
The orginal code works for me. But no idea about the compiler, so i'll look in to that. Will come back. But thanks that you trying to help

**Comment by G6EJD** [comment]
If the original code works then it is down to changes made to the code for port 8080.
Did you update the Domain Name Server address to match your network?

**Comment by Phanegem** [comment]
to be clear, 
i used your orginal code and did not change a thing, accept the ssid/password. It connects, (i can see it by scanning my network) but i can not reacht the server. Then i changed these line(s): href='yourip:port  

first i tried internal ip / 80, then internal 8080, then external 80 en dan external 8080. And i portforward tot the correct ip and port.

Tried to acces it through internal network, and external network. No luck.

Where can i change the orginal port, as i can not find this at the orginal code as wel.

**Comment by G6EJD** [comment]
Server.begin(80); to 8080
But this does sound like a compiler issue as the latest version does not work. As I mentioned downgrade the ESP826) to at least version 2.6 or the ESP32 to at least 3 versions earlier, you can see the versions in the drop down list

**Comment by Phanegem** [comment]
> Server.begin(80); to 8080 But this does sound like a compiler issue as the latest version does not work. As I mentioned downgrade the ESP826) to at least version 2.6 or the ESP32 to at least 3 versions earlier, you can see the versions in the drop down list

Oke, i'll try that and come back to you with the resulsts

**Comment by G6EJD** [comment]
I think you must have introduced a code error in your version, because I have just taken the code for the ESP32 and it works perfectly including for different port addresses.

**Comment by PetePenquin** [comment]
Hi, i promised to get back at you. I was just very blind, and looked at all the wrong places to get it solved. I did not saw the 5959 port. So this is solved, i got it goning.
Next question/request, if you willing to help of course.

I would like to add an OLED Display to show the temp live and the desired temp. I had this working on the 'old code' but doing the same in your code i get no compile error but the serial monitor says it can not find the bme sensor. 



`#include <Arduino.h>
//################# LIBRARIES ################
#include <WiFi.h>                      // Built-in
#include <ESPmDNS.h>                   // Built-in
#include <SPIFFS.h>                    // Built-in
#include "ESPAsyncWebServer.h"         // https://github.com/me-no-dev/ESPAsyncWebServer/tree/63b5303880023f17e1bca517ac593d8a33955e94
#include "AsyncTCP.h"                  // https://github.com/me-no-dev/AsyncTCP
#include <Wire.h>
#include <Adafruit_Sensor.h>           // Adafruit sensor
#include <Adafruit_BME280.h>           // For BME280 support
**#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>**
#define SEALEVELPRESSURE_HPA (1013.25)
Adafruit_BME280 sensor;                
               // I2C mode

//################ VARIABLES ###########################################

const char* ServerName = "thermostat"; // Connect to the server with http://hpserver.local/ e.g. if name = "myserver" use http://myserver.local/

#define SensorReadings  144            // maximum number of sensor readings, typically 144/day at 6-per-hour
#define NumOfSensors    2              // number of sensors (+1), set by the graphing section
#define NumOfEvents     4              // Number of events per-day, 4 is a practical limit
#define noRefresh       false          // Set auto refresh OFF
#define Refresh         true           // Set auto refresh ON
#define ON              true           // Set the Relay ON
#define OFF             false          // Set the Relay OFF
#define RelayPIN1        26              // Define the Relay Control pin
#define RelayPIN2        25
#define RelayPIN3        32
#define RelayPIN4        33
#define RelayReverse1    true          // Set to true for Relay that requires a signal LOW for ON
#define RelayReverse2    true
#define RelayReverse3    false
#define RelayReverse4    false
**#define SCREEN_WIDTH    128 // OLED display width, in pixels
#define SCREEN_HEIGHT   64 // OLED display height, in pixels**
#define SensorAddress   0x76           // Use 0x77 for an Adafruit variant
#define simulating      OFF            // Switch OFF for actual sensor readings, ON for simulated random values

typedef struct {
  float Temp  = 0;
  byte  Fahr  = 0;
  float Humi  = 0;
  byte  Press = 0;
  byte  Dewp  = 0;
  byte  Alti  = 0;
} sensordatatype;

sensordatatype sensordata[NumOfSensors][SensorReadings];

```
Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, -1);
Adafruit_BME280 BMP;
```

/\/\/\/\/\/\/\/

//#########################################################################################
void loop() {
     **display.clearDisplay();
    display.setTextSize(4);
    display.setCursor(5, 15);
    display.print(Temperature);
    display.print(" ");
    display.display();
    delay(1000);**  
  if ((millis() - LastTimerSwitchCheck) > TimerCheckDuration) {
    LastTimerSwitchCheck = millis();                      // Reset time
    ReadSensor();                                         // Get sensor readings, or get simulated values if 'simulated' is ON
    UpdateLocalTime();                                    // Updates Time UnixTime to 'now'
    CheckTimerEvent1();                                    // Check for schkTimerEvent2();
    CheckTimerEvent2();
  }
  if ((millis() - LastReadingCheck) > (LastReadingDuration * 60 * 1000)) {
    LastReadingCheck = millis();                          // Update reading record every ~n-mins e.g. 60,000uS = 1-min
    AssignSensorReadingsToArray();
  }
}
//#########################################################################################
`

**Comment by G6EJD** [comment]
You don’t need or have superseded the bme280 definition here:

Adafruit_BME280 BMP;
It was already defined as ‘sensor’
You don’t need to add ‘fahr’ field to the array just request temp °F from the bme280 instead of °C

Regards

David

**Comment by G6EJD** [comment]
It can’t find the sensor because you added:
Adafruit_BME280 BMP;

There’s no need to add the field ‘fahr’ just get °F from the bme280 as it can provide that saves a huge amount of storage.

**Pull request closed without merging**
